### ISSUE TITLE
Shipping To fields do not show after switching from Local Pickup Shipping Zone to another type of shipping zone

### ISSUE THREAD

**Issue by UVLabs** [fluidweb-co/fluid-checkout#54]
If you select a shipping method like "Local Pickup", FC will show the pickup point, then if you try to switch to another shipping method, it does not load the shipping fields, but if you then refresh the page while the other shipping method is selected, then FC will then show the shipping fields.

You can see this behaviour in this video: https://share.vidyard.com/watch/Ey5bcAnER4v5ntSCJLp7v1?

This happens in latest FC 1.5.8-beta1

FYI I did not have my plugin active while testing this issue

**Comment by diegoversiani** [comment]
Hi @UVLabs,

Thanks for reporting the problem.

This issue is related to the changes made to make the plugin compatible with your LPAC plugin (#47).

This has been fixed with 1.5.8-beta-3, which you can test from the link below:
https://t2449427.p.clickup-attachments.com/t2449427/5aa5057a-283a-4be0-ad34-cf948aa174e9/fluid-checkout-1.5.8-beta-3.zip

Best,
Diego
